ReportDefinitions:
- reportName: StreetVendingReport
  decryptionPathId: TradeLicenseDailyCollectionReport
  summary: Daily Register Report for street vending
  version: 1.0.0
  moduleName: sv-report
  sourceColumns:
  - name: application_no
    label: reports.sv.application_no
    type: string
    source: sv
    total: false
  - name: name
    label: reports.sv.name
    type: string
    source: sv
    total: false
  - name: locality
    label: reports.sv.locality
    type: string
    source: sv
    total: false
  - name: vending_activity
    label: reports.sv.vending_activity
    type: string
    source: sv
    total: false
  - name: vending_zone
    label: reports.sv.vending_zone
    type: string
    source: sv
    total: false
  - name: certificate_no
    label: reports.sv.certificate_no
    type: string
    source: sv
    total: false
  - name: application_status
    label: reports.sv.application_status
    type: string
    source: sv
    total: false
  - name: approvedby
    label: reports.sv.approvedby
    type: string
    source: sv
    total: false
  - name: amountpaid
    label: amoiuntpaid
    type: string
    source: sv
    total: false

  searchParams:
  - name: application_status
    label: reports.sv.application_status
    type: singlevaluelist
    pattern: 'list://APPLIED:Applied,APPROVED:Approved,REGISTRATIONCOMPLETED:Registration Completed,INSPECTIONPENDING:Inspection Pending,REJECTED:Rejected'
    source: sv
    isMandatory: false
    searchClause: AND sv.application_status = $application_status
  - name: vending_zone
    label: reports.sv.vending_zone
    type: singlevaluelist
    pattern: 'list://TEST_VALUE_ONE:TEST_VALUE_ONE,TEST_VALUE_TWO:TEST_VALUE_TWO'
    source: sv
    isMandatory: false
    searchClause: AND sv.vending_zone = $vending_zone
  - name: vending_activity
    label: reports.sv.vending_activity
    type: singlevaluelist
    pattern: 'list://STATIONARY:Stationary,MOBILE:Mobile'
    source: sv
    isMandatory: false
    searchClause: AND sv.vending_activity = $vending_activity
  - name: fromDate
    label: From Date
    type: epoch
    source: sv
    isMandatory: true
    searchClause: AND sv.createdtime >= $fromDate
  - name: toDate
    label: To Date
    type: epoch
    source: sv
    isMandatory: true
    searchClause: AND sv.createdtime  <= $toDate
