serviceMaps:
  serviceName: request-service
  mappings:
    - version: 1.0
      description: Persists water tanker application detail
      fromTopic: create-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_tanker_booking_details(booking_id, booking_no, tenant_id, address_detail_id, mobile_number, tanker_type, tanker_quantity, water_quantity, description, applicant_uuid, delivery_date, delivery_time, extra_charge, vendor_id, vehicle_id, driver_id, vehicle_type, vehicle_capacity, booking_createdby, booking_status, locality_code, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::DATE, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId
            - jsonPath: $.waterTankerBookingDetail.bookingNo
            - jsonPath: $.waterTankerBookingDetail.tenantId
            - jsonPath: $.waterTankerBookingDetail.addressDetailId
            - jsonPath: $.waterTankerBookingDetail.mobileNumber
            - jsonPath: $.waterTankerBookingDetail.tankerType
            - jsonPath: $.waterTankerBookingDetail.tankerQuantity
            - jsonPath: $.waterTankerBookingDetail.waterQuantity
            - jsonPath: $.waterTankerBookingDetail.description
            - jsonPath: $.waterTankerBookingDetail.applicantUuid
            - jsonPath: $.waterTankerBookingDetail.deliveryDate
            - jsonPath: $.waterTankerBookingDetail.deliveryTime
            - jsonPath: $.waterTankerBookingDetail.extraCharge
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.vehicleType
            - jsonPath: $.waterTankerBookingDetail.vehicleCapacity
            - jsonPath: $.waterTankerBookingDetail.bookingCreatedBy
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.localityCode
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdTime
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId

    - version: 1.0
      description: Update water tanker application detail
      fromTopic: update-water-tanker-booking
      isTransaction: true
      queryMaps:
        - query: UPDATE public.upyog_rs_tanker_booking_details SET booking_status = ?, vendor_id = ?, vehicle_id = ?, driver_id = ?, payment_receipt_filestore_id = ?, createdby = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingStatus
            - jsonPath: $.waterTankerBookingDetail.vendorId
            - jsonPath: $.waterTankerBookingDetail.vehicleId
            - jsonPath: $.waterTankerBookingDetail.driverId
            - jsonPath: $.waterTankerBookingDetail.paymentReceiptFilestoreId
            - jsonPath: $.waterTankerBookingDetail.auditDetails.createdBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.waterTankerBookingDetail.auditDetails.lastModifiedTime
            - jsonPath: $.waterTankerBookingDetail.bookingId

        - query: INSERT INTO public.upyog_rs_tanker_booking_details_auditdetails SELECT * FROM public.upyog_rs_tanker_booking_details WHERE booking_id = ?;
          basePath: waterTankerBookingDetail
          jsonMaps:
            - jsonPath: $.waterTankerBookingDetail.bookingId

    
    - version: 1.0
      description: Persists mobile toilet booking detail
      fromTopic: create-mobile-toilet-booking
      isTransaction: true
      queryMaps:
        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details(booking_id, booking_no, tenant_id, address_detail_id, mobile_number, no_of_mobile_toilet, delivery_from_date, delivery_to_date, delivery_from_time, delivery_to_time, description, applicant_uuid, vendor_id, vehicle_id, driver_id, booking_createdby, booking_status, locality_code, createdby, lastModifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?::DATE, ?::DATE, ?::TIME, ?::TIME, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId
            - jsonPath: $.mobileToiletBookingDetail.bookingNo
            - jsonPath: $.mobileToiletBookingDetail.tenantId
            - jsonPath: $.mobileToiletBookingDetail.addressDetailId
            - jsonPath: $.mobileToiletBookingDetail.mobileNumber
            - jsonPath: $.mobileToiletBookingDetail.noOfMobileToilet
            - jsonPath: $.mobileToiletBookingDetail.deliveryFromDate
            - jsonPath: $.mobileToiletBookingDetail.deliveryToDate
            - jsonPath: $.mobileToiletBookingDetail.deliveryFromTime
            - jsonPath: $.mobileToiletBookingDetail.deliveryToTime
            - jsonPath: $.mobileToiletBookingDetail.description
            - jsonPath: $.mobileToiletBookingDetail.applicantUuid
            - jsonPath: $.mobileToiletBookingDetail.vendorId
            - jsonPath: $.mobileToiletBookingDetail.vehicleId
            - jsonPath: $.mobileToiletBookingDetail.driverId
            - jsonPath: $.mobileToiletBookingDetail.bookingCreatedBy
            - jsonPath: $.mobileToiletBookingDetail.bookingStatus
            - jsonPath: $.mobileToiletBookingDetail.localityCode
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdTime
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedTime
        
        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details_auditdetails SELECT * FROM public.upyog_rs_mobile_toilet_booking_details WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId


    - version: 1.0
      description: Update mobile Toilet booking detail
      fromTopic: update-mobile-toilet-booking
      isTransaction: true
      queryMaps:
        - query: UPDATE public.upyog_rs_mobile_toilet_booking_details SET booking_status = ?, vendor_id = ?, vehicle_id = ?, driver_id = ?, payment_receipt_filestore_id = ?, createdby = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingStatus
            - jsonPath: $.mobileToiletBookingDetail.vendorId
            - jsonPath: $.mobileToiletBookingDetail.vehicleId
            - jsonPath: $.mobileToiletBookingDetail.driverId
            - jsonPath: $.mobileToiletBookingDetail.paymentReceiptFilestoreId
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.createdBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedBy
            - jsonPath: $.mobileToiletBookingDetail.auditDetails.lastModifiedTime
            - jsonPath: $.mobileToiletBookingDetail.bookingId

        - query: INSERT INTO public.upyog_rs_mobile_toilet_booking_details_auditdetails SELECT * FROM public.upyog_rs_mobile_toilet_booking_details WHERE booking_id = ?;
          basePath: mobileToiletBookingDetail
          jsonMaps:
            - jsonPath: $.mobileToiletBookingDetail.bookingId
